version: "3.2"
services:
  dev:
    container_name: node-template
    image: paritytech/ci-linux:3d903bdd-20210416
    deploy:
      resources:
        limits:
          memory: 2000M
    working_dir: /var/www/node-template
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/node-template/.cargo
    volumes:
      - .:/var/www/node-template
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/node-template --dev --ws-external"
